### ISSUE TITLE
Include areas that don't have plantings in by area view

### ISSUE THREAD

**Issue by paul121** [mstenta/farm_crop_plan#12]
This came up in the monthly call today (from @symbioquine). In the "by areas" view it would be nice to include areas that don't yet have plantings. Mostly for Planning purposes. This might be more useful once other logs are included in the visualization (Activities, Inputs, etc)

My first thought is that we could enable linking Areas to the Crop Plan entity (as is possible in other Plans). Then, the timeline could show all areas referenced by Plantings + all areas manually added to the Plan. Might not be that hard?

**Comment by mstenta** [comment]
This is a neat idea, but simply including all areas will not work for everyone. Larger farms may have hundreds of areas spread across multiple properties and it would not be helpful to include them in every plan.

A more nuanced approach might be to do something similar to what we did in the Grazing module: which is have a step during the plan setup process that allows you to select which areas are part of the plan.

I intentionally avoided this in the crop planning module initially, because it is an extra step, and it is much easier to just show the areas that are actually used. But I do see the value in having other areas included.

Not sure what the best way forward is, though... so I think we should give this more thought.

**Comment by mstenta** [comment]
We are in the process of porting this module to farmOS v3, and moving it to https://www.drupal.org/project/farm_crop_plan, along with any open issues that are still relevant.

Closing this as "not planned" but let's reopen in the new issue queue if we can think of a good way to address the core request/requirement.
