### ISSUE TITLE
Can only add single quantities

### ISSUE THREAD

**Issue by paul121** [mstenta/farm_crop_plan#2]
I took a first pass at adding quantities to the Crop Plan form.

- A single quantity can be saved on `seeding` and `transplanting` logs
  - `measure`, `value` and `units` fields are available.
- Can be saved with logs on new plantings, or new logs on existing plantings.
- If any part of the quantity changes, the quantity is updated on the log

One obvious limitation here is that we can only create one quantity per log.

But the larger issue is that the crop plan form only looks for the *first* quantity that was created on a log - we aren't using the `label` field, so there isn't an easy way to identify which quantities were created from the crop plan form. This also means that when modifying a quantity via the form, I have to delete all quantities from the log, and then create a new one.

Is the only solution here to search through all existing quantities and find the one which `measure` + `value` + `units` matches, and update accordingly?

**Comment by mstenta** [comment]
@paul121 and I discussed this and decided that the best next step is to change it so that it only updates the first quantity, rather than deleting all of them and recreating one.

Reasoning:

- Users may add additional quantities to logs manually, outside of the crop planning UI, and we don't want those to be automatically deleted.
- We can bake in the assumption that the "first" quantity on the log is always the one that the crop plan UI manages.  This would mean that if a user adds multiple quantities, and reorders them to put a different one first, then the crop plan UI would show that one instead.
- There will be a need for the crop plan UI to manage multiple quantities soon anyway. For example, when we add a "seeding calculator" we will want the option to store "total seeds (weight)" as well as perhaps "seeds per plug", etc.

**Comment by mstenta** [comment]
> change it so that it only updates the first quantity, rather than deleting all of them and recreating one.

FYI @paul121 made this change: https://github.com/mstenta/farm_crop_plan/commit/e1c7bd8e6a5cb98b22dc2c7b2798320bd4a1efa3
