### ISSUE TITLE
Ideas for improving crop plan workflows

### ISSUE THREAD

**Issue by mstenta** [mstenta/farm_crop_plan#30]
Eliza at Wolfe's Neck had some valuable thoughts in the OpenTEAM Hub + Tech working group call today. Copying here to continue the conversation and brainstorming...

> for us in crop production at WNC- we need something very teachable and intuitive for our apprentices, mobile-friendly, fast and searchable because so much happens in a day, we can seed and transplant and harvest all in the same day, and if it takes us 30+ mins every day to record keep we won’t do it. We basically need something that rivals our google spreadsheet for us to realistically use it

**Comment by ludwa6** [comment]
Ah... In light of [this video from over >1 year ago](https://drive.google.com/file/d/1jjeBY_EOPWQayCfslodICnRdlq3peGsq/view), i kinda expected that Crop Planning in farmOS was already in production use, at Wolf's Neck at least, even if nowhere else. 

For my part: i haven't yet had a chance to try it (is not available at Farmier, AFAIK -right @mstenta ?), but i am curious: can we get a status update and outlook on planned developments?

I ask because i'm also keen to get off our spreadsheet-based crop plan (has grown too big and unwieldy), and am entertaining a proposal to roll our own solution in some other more general-purpose software (e.g. Notion), but i would very much rather do it in farmOS, if possible!

**Comment by mstenta** [comment]
@ludwa6 see my reply to your email regarding enabling this on your Farmier-hosted instance. The main consideration is that it is not available for farmOS 2.x, and therefore means an additional hurdle to your eventual upgrade.

There are a handful of farms using this (still very "beta") module in production that I'm aware of (including myself) - but it is still very limited in what it can do. Wolfe's Neck beta tested in last year, and we plan to work together more this year to improve upon it when we tackle porting it to farmOS 2.x. Small steps and sights on the horizon...

There is no timeline, sorry. If you are interested in contributing resources to the initiative please feel free to reach out to me via email. Our hands are quite full with the general farmOS 2.x upgrade at the moment, so unfortunately I can't provide much more help/insight on the future beyond that right now.

**Comment by ludwa6** [comment]
Thanks @mstenta : as discussed by email, i'll be exploring this module as it stands (now that it's available in my Farmier instance -and thanks for the speedy deployment there!), and will then evaluate it's potential value as a solution for my operation.  

Meanwhile: Rock on w/ that farmOS 2.x upgrade, Mike; that's the main event -and i look forward to assisting w/ the migration test!

**Comment by mstenta** [comment]
Update! (And a new place to continue discussions...)

https://farmos.discourse.group/t/farmos-crop-plan-module-v3-alpha-release/1934

In regards to the original issue description:

> We basically need something that rivals our google spreadsheet for us to realistically use it

I'm hoping to pursue a "hybrid" approach in the new v3 module, which will have the ability to export/import a CSV to update the crop plan in farmOS, so most day-to-day updates can still happen outside of farmOS in whatever spreadsheet application folks are already using. I will provide updates in the forum...
