### ISSUE TITLE
Show other logs associated with plantings as dots/icons

### ISSUE THREAD

**Issue by mstenta** [mstenta/farm_crop_plan#6]

**Comment by mstenta** [comment]
Maybe wait for https://github.com/mstenta/farm_crop_plan/issues/7

**Comment by jgaehring** [comment]
Just want to posit some ideas we discussed in chat. Primarily, the idea of using icons for all the logs, including Seeding, Transplanting and Harvest logs. We could distinguish them as unique icons at the boundary of each stage:

![image](https://user-images.githubusercontent.com/5556545/86470157-d63e0c00-bd08-11ea-85d7-2c3966b49d1f.png)

A triangle represents a Seeding log, diamond a Transplanting log, and square a Harvest log (or logs). Other logs could shown as dots (perhaps a little smaller, to emphasize the main logs).

Then on hover, click or tap (for mobile), a tool tip would be revealed above the icon, showing the log name (as a link), and possibly some other details like location:

![image](https://user-images.githubusercontent.com/5556545/86470619-c4109d80-bd09-11ea-98b0-71e933a60de1.png)

Note that along with the tool tip, there is also a chevron below the icon; when clicked, this will expand the [drop-down form](https://www.figma.com/proto/q9YnrQPoLBLaKu5thlx6Td/Form-Components?node-id=30%3A25&scaling=min-zoom). And because these overlays can be displayed on hover/click/tap, it should still allow for drag-and-drop interactions using press-and-hold, with the icon itself providing a nice "handle" for the operation.

The main effect of this is that we no longer need to include the log name and other info within the rows themselves. That will make it possible for the rows to be a lot smaller along the y-axis, which will allow more rows to fit on the screen at once, while also keeping them at a more consistent height. It should also help keep lengths more consistent along the x-axis, so days/weeks/etc are always spaced at regular intervals. In general I believe it should convey more info at a glance, especially as the user learns to parse the different icons for their log type, although it may be helpful to include some kind of legend at the top of the timeline.

A secondary effect would be that the drop-down forms would now be more closely associated with the logs themselves, rather than the ranges between the logs. I feel like this makes more semantic sense, since most of the details in each form pertain to the log itself, with the notable exception being Days to Transplant/Harvest (perhaps this number could still be displayed/edited within the row itself, if space allows, since it should always be a small amount of text).

**Comment by mstenta** [comment]
This is done in the new 3.x branch! :tada: 

See the screenshot (and continue the brainstorming!) in this forum topic: https://farmos.discourse.group/t/farmos-crop-plan-module-v3-alpha-release/1934
